### ISSUE TITLE
Dockerfile fails to install agents repo correctly and other dockerfile issues

### ISSUE THREAD

**Issue by shivanimall** [tonyzhaozh/meld#2]
```
ADD ../agents-0.3.0 /root/agents-0.3.0
RUN pip install -e /root/agents-0.3.0

```
these fail since the path and dir name is incorrect.

Here is the exact error- 
```
Step 37/38 : ADD ../agents-0.3.0 /root/agents-0.3.0
ADD failed: Forbidden path outside the build context: ../agents-0.3.0 ()
```

**Comment by shivani1494** [comment]
also, why is the $LD_LIBRARY_PATH differently set using instructions anaconda and Dockerfile?

**Comment by shivanimall** [comment]
why is LD_LIBRARY_PATH not set in the dockerfile to point to cuda-10 and nvidia driver?

**Comment by shivanimall** [comment]
Error-- Getting "Failed to Initialize OpenGL" 

is there a resolution for this?

Also, from the Dockerfile comments--
hoping this fixes opengl error
(TODO) figure out if this does anything
ENV DISPLAY :0

is there a resolution for this?

I saw this- 
https://stackoverflow.com/questions/41741100/run-opengl-on-aws-gpu-instances-with-ubuntu 

-- this post has some resolution but there are errors starting Xorg server from inside a docker container- from vi /var/log/Xorg.0.log error is
dbus-core: error connecting to system bus: org.freedesktop.DBus.Error.FileNotFound (Failed to connect t
o socket /var/run/dbus/system_bus_socket: No such file or directory)

**Comment by katerakelly** [comment]
Hi @shivani1494 

Sorry for the very long time it took to reply to your issue!
I have corrected the typos in the Dockerfile. When I build from scratch on my machine, it works - I don't get the OpenGL error you mention. If this is still a problem for you, could you provide more details of your setup?

**Comment by shivanimall** [comment]
Hi @katerakelly, thanks for the response.

what is your environment like? are you running the dockerfile on a VM(google cloud/AWS) or on a local machine?

**Comment by katerakelly** [comment]
I tested this installation on a local machine. We also used GCP previously with the same docker container.

Maybe it has something to do with the CUDA version or the nvidia-driver version on the VM you create? I remember in GCP, it required some care to get the "base image" right.
