### ISSUE TITLE
no module named  "meld"

### ISSUE THREAD

**Issue by csufangyu** [tonyzhaozh/meld#3]
hi , I have try to run your code,but I get a error,can you hlep me?

```
(meld) fangyu@Robot-DGX-Station:~/robot_learning/meld$ CUDA_VISIBLE_DEVICES=0 python meld/scripts/run_meld.py \
>   --root_dir save_dir \
>   --experiment_name dense_sawyerReacher \
>   --gin_file meld/configs/0_meld_dense.gin \
>   --gin_file meld/configs/1_sawyerReacher.gin \
>   --gin_file meld/configs/2_sawyerReacher_1episode.gin
Traceback (most recent call last):
  File "meld/scripts/run_meld.py", line 27, in <module>
    from meld.utils.env_drivers import DynamicTrialDriver
ModuleNotFoundError: No module named 'meld'
```

**Comment by tonyzhaozh** [comment]
- Make sure path is set correctly for each of newly opened shell:
```bash
export PYTHONPATH=<path_to_meld>
export LD_PRELOAD=''
```
^ make sure you followed these two steps in Readme! lmk if problem persists

**Comment by csufangyu** [comment]
thanks，I reset my computer,and it become ok!

**Comment by Schortenger** [comment]
Hi, fangyu @csufangyu ,

I guess you have run this code successfully. Right?
Have you ever met some errors showing "Segmentation Fault(core dumped)", as this issue shows: https://github.com/tonyzhaozh/meld/issues/5
Looking forward to your advice.

**Comment by csufangyu** [comment]
hi I have not got this error，but it maybe caused by mujoco. Do you want to render and use camera at the same time?

**Comment by Schortenger** [comment]
@csufangyu 
Hi, thank you for your fast reply.
May I ask that how many GPUs have you used when you run this code?

**Comment by csufangyu** [comment]
sorry,I didn't notice it.There are 4 V100 in my  computing server.
