### ISSUE TITLE
Segmentation Falut(core dumped) Problem  (for both GPU and CPU)

### ISSUE THREAD

**Issue by newuhe** [tonyzhaozh/meld#5]
My setting is Tesla V100 with 32g graphics memory,  4-core CPU and 32g memory. When I run script `CUDA_VISIBLE_DEVICES=0 python meld/scripts/run_meld.py \
  --root_dir save_dir \
  --experiment_name dense_cheetah \
  --gin_file meld/configs/0_meld_dense.gin \
  --gin_file meld/configs/1_cheetahVel.gin \
  --gin_file meld/configs/2_cheetahVel_1episode.gin`

It throws out the problem
`Global step 0: Beginning init collect op with random policy. Collecting 20x {50, 1} trials for each task
I0423 18:47:10.212495 139888148100864 run_meld.py:824] on task 1 / 20
Fatal Python error: Segmentation fault`
`File "/home/flexivsu/anaconda3/envs/meld/lib/python3.6/site-packages/absl/app.py", line 299 in run
  File "meld/scripts/run_meld.py", line 1023 in <module>
Segmentation fault (core dumped)`

and the nvidia-smi status is as following:
![3421619176321_ pic](https://user-images.githubusercontent.com/22556351/115996105-8f5f3100-a610-11eb-8adb-1b69a900d486.jpg)
It seems the multi-thread sampling costs too much graphic memeroy.

However, when i try to use cpu instead to run the scirpt, it also throws out the same problem, and the cpu and memory occupancy is:
![3451619176612_ pic_hd](https://user-images.githubusercontent.com/22556351/115996198-e402ac00-a610-11eb-8758-4f678ffdcc9f.jpg)
I'm wondering what is the problem since the memory and cpu occupancy are both within limit. Does anybody answer me?  I'm stuck in the problem days and nights.........

**Comment by newuhe** [comment]
@tonyzhaozh @katerakelly

**Comment by tonyzhaozh** [comment]
Hi Junfeng,

Right now I probably don't have the exact solution to the errors you posted: I've never run into segfault for meld and it is also a bit weird that a single cheetah experiment takes all those memory. However, one thing that you could try is adding:

`  --gin_param train_eval.gpu_memory_limit=7500`

to your command. The 7500 is the maximum gpu memory it is allowed to use and in our experiments we find that sufficient. 

Please let us know if adding this helps solve the issue.

Best,
Tony

Edit: apparently i was wrong here and we did run into segfault for the mujoco rendering thing. Pls see the thread below

**Comment by Schortenger** [comment]
Hi Tony,
Thank you for your fast reply. We tried to add `--gin_param train_eval.gpu_memory_limit=7500` in our command, and the memory seems better than before, but the result remains as "Segmentation Fault (core dumped)". Do you have any other suggestions? Actually, we have been stuck in this problem for weeks......
The NVIDIA memory is as following:
![image](https://user-images.githubusercontent.com/45628325/116179878-9e49fe80-a74a-11eb-816a-abb5c05ecd0d.png)
The final result is:
![Selection_012](https://user-images.githubusercontent.com/45628325/116180154-0862a380-a74b-11eb-902c-600c6c188a7b.png)
Looking forward to your help. Thank you. @tonyzhaozh @katerakelly

**Comment by tonyzhaozh** [comment]
ah i think i know what is happening, see
https://github.com/tonyzhaozh/meld/blob/master/meld/utils/env_utils.py#L77
There is this weird rendering quirk of mujoco that when you render two envs (in our case train env and eval env) in one gpu, it segfaults.

I do not have a direct solution to this problem unfortunately. Probably the easiest way is to find a machine that has two gpus.

edit: alternatively you can try to edit the code and just delete all appearances of eval env. but that also seems pretty tricky

**Comment by tonyzhaozh** [comment]
I am sorry for the frustrations it caused, and I will update this to the repo. Thanks a lot for the feedback and please let me know if it works out / any problems.

-Tony

**Comment by Schortenger** [comment]
Hi, Tony,

Thank you for your reply. Under your advice, we add one more GPU. As this image shows:
![Selection_013](https://user-images.githubusercontent.com/45628325/116225401-5ba51800-a784-11eb-9fa2-b396e08a1709.png)
![Selection_014](https://user-images.githubusercontent.com/45628325/116225581-98710f00-a784-11eb-8308-8802e7b16ded.png)

But the result doesn't change. I guess maybe it's because the 2nd GPU was not used, as the used memory of 2nd GPU is always 0MiB shown in `nvidia-smi.` Do you know how to change this?

**Comment by tonyzhaozh** [comment]
I'm not sure what is causing this hmm the rendering should take 27mb in both gpus

**Comment by Schortenger** [comment]
Hi, Tony,

Thank you for your valuable advice. I delete the original 'meld' folder and download everything again. Now the 2nd GPU is detected, and everything is OK, as this image shows:
![Selection_016](https://user-images.githubusercontent.com/45628325/116363083-5522a900-a835-11eb-9eee-eb1888a2e2a4.png)

Besides, if I want to look at the rendering image while training, do you know how to make it?

**Comment by tonyzhaozh** [comment]
Great!

We save eval/train videos periodically to tensorboard. Please check the example usage section in Readme for instructions.

-Tony

**Comment by Schortenger** [comment]
Dear Tony,

Thank you for your reply.

As I understand, the codes below are used to produce rendering videos:
```
class VideoWrapper(wrappers.PyEnvironmentBaseWrapper):
  def __init__(self, env):
    """Wrapper that keeps track of frames that are rendered after every step.

    It is useful when this environment is wrapped by an ActionRepeat wrapper,
    in which the latter would not be able to render the frames in between steps.
    The `frames` buffer is unbounded and it should be periodically emptied
    elsewhere outside of this class.
    """
    super(VideoWrapper, self).__init__(env)
    self._frames = []
    self._rendering = True
```
However, as I have changed `self._rendering` as `True`, there are no videos output in `save_dir`.
Could you please tell me how to produce and save the rendering video in train\eval process? I found no instructions on Readme and the `examples.txt`. 
Looking forward to your reply. Thank you.

**Comment by tonyzhaozh** [comment]
Hi, so we do not save videos directly (e.g. in mp4) but save it with the tensorflow logger. To obtain logged videos (in GIF format) you need to use GUI of tensorboard.

https://github.com/tonyzhaozh/meld/blob/master/meld/utils/eval_summaries.py#L339

^ is the code where we save videos with tf logger. You should also be able to use libraries like skvideo to save `render_images` as mp4 after proper reshaping.

I will be closing this issue but feel free to open a new one.

-Tony
