### ISSUE TITLE
Question about the training hours

### ISSUE THREAD

**Issue by Schortenger** [tonyzhaozh/meld#6]
May I ask you about that how long does the whole training process take on your system, with what kind of system setup?
I find that MELD needs more about 0.2 millions env steps to succeed for peg insertion task, based on your paper. I trained it on my computer, but it needs nearly 8 days (~186 hours) to finish 0.128 millions steps. 
My setting is 2*Tesla V100 with 32g graphics memory, 12-core CPU with 32g memory.

I am confused about the training time? It's really so long. How about your training? If not, do you have some ideas to speed up the process?

**Comment by tonyzhaozh** [comment]
Hi Teng, training should definitely not take that long. For reference, we can launch 8 experiments in our server (8*v100, 40-core cpu) and expect ~0.2M steps overnight. 

I would suggest checking whether gpu is getting utilized for training. E.g. nvidia-smi should show pretty high usage percentage and htop should not.

**Comment by Schortenger** [comment]
Hi,  Tony,
Thank you for your help. I launched 3 experiments in my server. My `nvidia-smi` and `htop` shows as below:

![Selection_019](https://user-images.githubusercontent.com/45628325/119594302-1a993580-be0e-11eb-9cf0-016cd1971944.png)

![Selection_020](https://user-images.githubusercontent.com/45628325/119594304-1c62f900-be0e-11eb-8563-176c42a0b72e.png)


It seems that htop is fully used, while gpu is not. I guess it's due to the rendering of mujoco envs, which doesn't support GPU. See: 
[https://github.com/tonyzhaozh/meld/blob/master/meld/scripts/run_meld.py#L493](https://github.com/tonyzhaozh/meld/blob/master/meld/scripts/run_meld.py#L493)

 Do you agree with that? Does this mean my training is not based on gpu? If so, do you know how to fix it?

**Comment by tonyzhaozh** [comment]
Hi Teng,

The line you pointed to is when we noticed the tf_agent replay buffer cannot be loaded to the GPU's memory and it will thus stay inside RAM. I don't think this relates to the training issued above.

From the screenshot: the training is not using GPU at all. You can see the memory is mostly empty and usage is 0%. When we run it each experiment could take >7000mb and >70% of a single gpu. 

You might want to double check your tensorflow is installed correctly: make sure it is tensorflow-gpu (see [this](https://github.com/tonyzhaozh/meld/blob/master/docker/environment.yml#L22))

**Comment by Schortenger** [comment]
Hi, Tony,

Thanks for your guidence. I think I have found my problem. I forgot to `export` CUDA path, so that tensorboard-gpu cannot be utilized. I add the path in ~/.bashrc:
```
export CUDA_HOME=/usr/local/cuda
export PATH=$PATH:$CUDA_HOME/bin
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```

Now everything is fine. Thank you.
![Selection_022](https://user-images.githubusercontent.com/45628325/119618427-75925300-be35-11eb-9c3d-bb75dcb93cf3.png)
